In [3]:
from pyFTracks.annealing import chi_square
from scipy.stats import chi2
from pyFTracks.ressources import Miller1995
from pyFTracks.ressources import Gleadow

In [4]:
Miller1995

    Grain  ...  Unit Area $10^6 \text{cm}^2$
0       1  ...                        0.9009
1       2  ...                        0.9009
2       3  ...                        0.9009
3       4  ...                        0.9009
4       5  ...                        0.9009
5       6  ...                        0.9009
6       7  ...                        0.9009
7       8  ...                        0.9009
8       9  ...                        0.9009
9      10  ...                        0.9009
10     11  ...                        0.9009
11     12  ...                        0.9009
12     13  ...                        0.9009
13     14  ...                        0.9009
14     15  ...                        0.9009
15     16  ...                        0.9009
16     17  ...                        0.9009
17     18  ...                        0.9009
18     19  ...                        0.9009
19     20  ...                        0.9009

[20 rows x 9 columns]

In [5]:
Ns = Miller1995["Ns (Number of spontaneous tracks)"]
Ni = Miller1995["Ni (Number of induced tracks)"]

In [6]:
chi_square(Ns, Ni)

0.9292129985459694

In [11]:
Gleadow

    Grain  ...  Unit Area $10^6 \text{cm}^2$
0       1  ...                          0.78
1       2  ...                          0.78
2       3  ...                          0.78
3       4  ...                          0.78
4       5  ...                          0.78
5       6  ...                          0.78
6       7  ...                          0.78
7       8  ...                          0.78
8       9  ...                          0.78
9      10  ...                          0.78
10     11  ...                          0.78
11     12  ...                          0.78
12     13  ...                          0.78
13     14  ...                          0.78
14     15  ...                          0.78
15     16  ...                          0.78
16     17  ...                          0.78
17     18  ...                          0.78
18     19  ...                          0.78
19     20  ...                          0.78
20     21  ...                          0.78
21     22  ...                          0.78
22     23  ...                          0.78
23     24  ...                          0.78
24     25  ...                          0.78
25     26  ...                          0.78
26     27  ...                          0.78
27     28  ...                          0.78
28     29  ...                          0.78
29     30  ...                          0.78

[30 rows x 9 columns]

In [7]:
Ns = Gleadow["Ns (Number of spontaneous tracks)"]
Ni = Gleadow["Ni (Number of induced tracks)"]

In [8]:
chi_square(Ns, Ni)

0.0