In [1]:
import pandas as pd

Spontaneous and Induced track counts from 30 Apatites grains from the Mahe Granite, Seychelles. Table 3.3 from Galbraith book. Data originally provided by A. Gleadow

In [2]:
data = pd.DataFrame()

In [3]:
data["Grain"] = range(1,31)
data["Ns (Number of spontaneous tracks)"]   = [0, 2, 18, 2, 10, 3, 4, 20, 52, 2, 1, 6, 256, 52, 3, 10, 2, 7, 1, 14, 15, 14, 8, 22, 16, 34, 14, 6, 13, 127]
data["Ni (Number of induced tracks)"]   = [11, 11, 28 ,4, 78, 22, 8, 57, 129, 7, 9, 16, 220, 134, 11, 17, 5, 23, 10, 43, 44, 25, 28, 69, 29, 51, 56, 9, 22, 213]
data["Area (Number of graticules squares)"] = [24, 44, 32, 40, 90, 30, 40, 50, 20, 45, 35, 50, 100, 24, 35, 16, 12, 40, 60, 24, 49, 48, 32, 45, 44, 35, 40, 5, 32, 28]
data["$\zeta$ $\text{Ma} \times 10^{6} \text{cm}^{2}$"] = 380.0
data["$\zeta$ rel. std. error"] = 5.0 / 380.0
data["$N_d$"] = 2936
data["$\rho_d$ $10^6 \text{cm}^2$"] = 1.257
data["Unit Area $10^6 \text{cm}^2$"] = 0.78

In [4]:
data

,Grain,Ns (Number of spontaneous tracks),Ni (Number of induced tracks),Area (Number of graticules squares),$\zeta$ $\text{Ma} \times 10^{6} \text{cm}^{2}$,$\zeta$ rel. std. error,$N_d$,$\rho_d$ $10^6 \text{cm}^2$,Unit Area $10^6 \text{cm}^2$
0,1,0,11,24,380.0,0.013158,2936,1.257,0.78
1,2,2,11,44,380.0,0.013158,2936,1.257,0.78
2,3,18,28,32,380.0,0.013158,2936,1.257,0.78
3,4,2,4,40,380.0,0.013158,2936,1.257,0.78
4,5,10,78,90,380.0,0.013158,2936,1.257,0.78
5,6,3,22,30,380.0,0.013158,2936,1.257,0.78
6,7,4,8,40,380.0,0.013158,2936,1.257,0.78
7,8,20,57,50,380.0,0.013158,2936,1.257,0.78
8,9,52,129,20,380.0,0.013158,2936,1.257,0.78
9,10,2,7,45,380.0,0.013158,2936,1.257,0.78
10,11,1,9,35,380.0,0.013158,2936,1.257,0.78
11,12,6,16,50,380.0,0.013158,2936,1.257,0.78
12,13,256,220,100,380.0,0.013158,2936,1.257,0.78
13,14,52,134,24,380.0,0.013158,2936,1.257,0.78
14,15,3,11,35,380.0,0.013158,2936,1.257,0.78
15,16,10,17,16,380.0,0.013158,2936,1.257,0.78
16,17,2,5,12,380.0,0.013158,2936,1.257,0.78
17,18,7,23,40,380.0,0.013158,2936,1.257,0.78
18,19,1,10,60,380.0,0.013158,2936,1.257,0.78
19,20,14,43,24,380.0,0.013158,2936,1.257,0.78
20,21,15,44,49,380.0,0.013158,2936,1.257,0.78
21,22,14,25,48,380.0,0.013158,2936,1.257,0.78
22,23,8,28,32,380.0,0.013158,2936,1.257,0.78
23,24,22,69,45,380.0,0.013158,2936,1.257,0.78
24,25,16,29,44,380.0,0.013158,2936,1.257,0.78
25,26,34,51,35,380.0,0.013158,2936,1.257,0.78
26,27,14,56,40,380.0,0.013158,2936,1.257,0.78
27,28,6,9,5,380.0,0.013158,2936,1.257,0.78
28,29,13,22,32,380.0,0.013158,2936,1.257,0.78
29,30,127,213,28,380.0,0.013158,2936,1.257,0.78

In [5]:
from pandas import HDFStore

In [6]:
Gleadow = HDFStore("Gleadow.h5")

In [7]:
Gleadow["data"] = data

In [9]:
Gleadow.close()

In [10]:
Gleadow = pd.read_hdf("Gleadow.h5", "data")

In [11]:
Gleadow.columns

Index(['Grain', 'Ns (Number of spontaneous tracks)',
       'Ni (Number of induced tracks)', 'Area (Number of graticules squares)',
       '$\zeta$ $\text{Ma} \times 10^{6} \text{cm}^{2}$',
       '$\zeta$ rel. std. error', '$N_d$', '$\rho_d$ $10^6 \text{cm}^2$',
       'Unit Area $10^6 \text{cm}^2$'],
      dtype='object')

In [12]:
Gleadow

,Grain,Ns (Number of spontaneous tracks),Ni (Number of induced tracks),Area (Number of graticules squares),$\zeta$ $\text{Ma} \times 10^{6} \text{cm}^{2}$,$\zeta$ rel. std. error,$N_d$,$\rho_d$ $10^6 \text{cm}^2$,Unit Area $10^6 \text{cm}^2$
0,1,0,11,24,380.0,0.013158,2936,1.257,0.78
1,2,2,11,44,380.0,0.013158,2936,1.257,0.78
2,3,18,28,32,380.0,0.013158,2936,1.257,0.78
3,4,2,4,40,380.0,0.013158,2936,1.257,0.78
4,5,10,78,90,380.0,0.013158,2936,1.257,0.78
5,6,3,22,30,380.0,0.013158,2936,1.257,0.78
6,7,4,8,40,380.0,0.013158,2936,1.257,0.78
7,8,20,57,50,380.0,0.013158,2936,1.257,0.78
8,9,52,129,20,380.0,0.013158,2936,1.257,0.78
9,10,2,7,45,380.0,0.013158,2936,1.257,0.78
10,11,1,9,35,380.0,0.013158,2936,1.257,0.78
11,12,6,16,50,380.0,0.013158,2936,1.257,0.78
12,13,256,220,100,380.0,0.013158,2936,1.257,0.78
13,14,52,134,24,380.0,0.013158,2936,1.257,0.78
14,15,3,11,35,380.0,0.013158,2936,1.257,0.78
15,16,10,17,16,380.0,0.013158,2936,1.257,0.78
16,17,2,5,12,380.0,0.013158,2936,1.257,0.78
17,18,7,23,40,380.0,0.013158,2936,1.257,0.78
18,19,1,10,60,380.0,0.013158,2936,1.257,0.78
19,20,14,43,24,380.0,0.013158,2936,1.257,0.78
20,21,15,44,49,380.0,0.013158,2936,1.257,0.78
21,22,14,25,48,380.0,0.013158,2936,1.257,0.78
22,23,8,28,32,380.0,0.013158,2936,1.257,0.78
23,24,22,69,45,380.0,0.013158,2936,1.257,0.78
24,25,16,29,44,380.0,0.013158,2936,1.257,0.78
25,26,34,51,35,380.0,0.013158,2936,1.257,0.78
26,27,14,56,40,380.0,0.013158,2936,1.257,0.78
27,28,6,9,5,380.0,0.013158,2936,1.257,0.78
28,29,13,22,32,380.0,0.013158,2936,1.257,0.78
29,30,127,213,28,380.0,0.013158,2936,1.257,0.78